### ISSUE TITLE
ios: can`t select image  on ios when user status == .limited

### ISSUE THREAD

**Issue by secreter** [baronha/react-native-multiple-image-picker#125]
My ios version is 16.1.1, npm version is 1.1.5。when user status == .limited，can`t select image success, when I click ok, I see an Error:
my config :
```
usedCameraButton: true,
  mediaType: 'image',
  allowedPhotograph: true,
```
> Error: User has canceled
    at promiseMethodWrapper (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:2799:45)
    at ?anon_0_ (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:286515:89)
    at next (native)
    at asyncGeneratorStep (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:28322:26)
    at _next (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:28341:29)
    at anonymous (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:28346:14)
    at tryCallTwo (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:28338:25)
    at apply (native)
    at anonymous (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:286529:26)
    at tryCallTwo (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:82:14)
    at openPicker (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:286512:23)
    at ?anon_0_ (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:286354:123)
    at next (native)
    at asyncGeneratorStep (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:28322:26)
    at _next (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:28341:29)
    at anonymous (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:28346:14)
    at tryCallTwo (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:28338:25)
    at apply (native)
    at addMultipleImage (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:286362:27)
    at ?anon_0_ (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:286331:33)
    at next (native)
    at asyncGeneratorStep (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:28322:26)
    at _next (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:28341:29)
    at anonymous (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:28346:14)
    at tryCallTwo (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:28338:25)
    at apply (native)
    at handleAddImage (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:286335:27)
    at _performTransitionSideEffects (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:65152:22)
    at _receiveSignal (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:65102:45)
    at onResponderRelease (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:64958:34)
    at apply (native)
    at invokeGuardedCallbackProd (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:81241:21)
    at apply (native)
    at invokeGuardedCallback (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:81417:42)
    at apply (native)
    at invokeGuardedCallbackAndCatchFirstError (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:81431:36)
    at executeDispatch (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:81508:48)
    at executeDispatchesInOrder (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:81530:26)
    at executeDispatchesAndRelease (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:83303:35)
    at executeDispatchesAndReleaseTopLevel (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:83310:43)
    at forEach (native)
    at forEachAccumulated (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:82124:22)
    at runEventsInBatch (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:83323:27)
    at runExtractedPluginEventsInBatch (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:83433:25)
    at anonymous (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:83404:42)
    at batchedUpdates$1 (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:96869:20)
    at batchedUpdates (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:83279:36)
    at _receiveRootNodeIDEvent (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:83403:23)
    at receiveTouches (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:83492:34)
    at apply (native)
    at __callFunction (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:3290:36)
    at anonymous (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:3010:31)
    at __guard (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:3227:15)
    at callFunctionReturnFlushedQueue (http://192.168.18.202:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.imeikan.app:3009:21)
 WARN  Possible Unhandled Promise Rejection (id: 2):
Error: User has canceled

**Comment by baronha** [comment]
Check new version: [2.0](https://github.com/baronha/react-native-multiple-image-picker/releases/tag/2.0)
Docs: https://baronha.github.io/react-native-multiple-image-picker/
