### ISSUE TITLE
[Android] Keeps Crashing When Pressing Photo on CameraRoll

### ISSUE THREAD

**Issue by tronginc** [baronha/react-native-multiple-image-picker#39]
I have pressed on the photo then my app crashes.

![image](https://user-images.githubusercontent.com/33952884/131215621-51062749-fb0c-48f4-acaa-0dea9fc12de8.png)

Logs

```
AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/yalantis/ucrop/UCrop$Options;
AndroidRuntime:        at com.luck.picture.lib.PictureSelector.openGallery(PictureSelector.java:71)
AndroidRuntime:        at com.reactnativemultipleimagepicker.MultipleImagePickerModule.openPicker(MultipleImagePickerModule.kt:52)
AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime:        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
AndroidRuntime:        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
AndroidRuntime:        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27
)
AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
AndroidRuntime:        at java.lang.Thread.run(Thread.java:923)
AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.yalantis.ucrop.UCrop$Options" on path: DexPathLis
t[[zip file "/data/app/~~vqM-cME_je1c7s0seLooqQ==/com.example-Md21MKbEL7n4eeYER9lF2g==/base.apk"],nativeLibraryDirectories=[/data/app/~~vqM-cME_je1c7s0seLo
oqQ==/com.example-Md21MKbEL7n4eeYER9lF2g==/lib/x86_64, /data/app/~~vqM-cME_je1c7s0seLooqQ==/com.example-Md21MKbEL7n4eeYER9lF2g==/base.apk!/lib/x
86_64, /system/lib64, /system_ext/lib64]]
AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
AndroidRuntime:        ... 12 more
ActivityTaskManager:   Force finishing activity com.example/com.luck.picture.lib.PicturePreviewActivity
DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
goldfish-address-space: claimShared: Ask to claim region [0x3e1b0a000 0x3e201a000]
ActivityTaskManager:   Force finishing activity
```

**Comment by tronginc** [comment]
Sorry for the duplicate issue #9 #30.
But it still happened!
`"@baronha/react-native-multiple-image-picker": "^0.4.1"`

**Comment by Imtayaz** [comment]
Yes ! I do have same issue with iOS and Android - Emulator

**Comment by hungdev** [comment]
hope it gets fixed soon @baronha

**Comment by uplamartya** [comment]
I do have same issue with iOS physical device

**Comment by baronha** [comment]
@Hi guys. Check last version(0.4.5). If this is still happening, please leave a comment below. There are some small changes in the setup for Android. Check [README](https://github.com/baronha/react-native-multiple-image-picker#android).
