### ISSUE TITLE
Error when touch on the photo selection

### ISSUE THREAD

**Issue by MinhNNDev** [baronha/react-native-multiple-image-picker#9]
Hi, that is great pakage, config pakage so easy, fast. But when touch on the photo selection, it action good while i touch to circle, but when I touch outside of the circle (background) the app crashes (Android)

**Comment by baronha** [comment]
Which OS do you use? Is it Android??

**Comment by MinhNNDev** [comment]
> Which OS do you use? Is it Android??

Yepp !!! Android

**Comment by Seu07** [comment]
yes on android, if sometime if we press or scroll fast so it crash in android.

**Comment by ymane** [comment]
Yes I am also facing same issue in Android  11
` java.lang.NoClassDefFoundError: Failed resolution of: Lcom/luck/picture/lib/config/UCropOptions;
        at com.luck.picture.lib.config.PictureSelectionConfig.<init>(PictureSelectionConfig.java:477)
        at com.luck.picture.lib.config.PictureSelectionConfig$1.createFromParcel(PictureSelectionConfig.java:516)
        at com.luck.picture.lib.config.PictureSelectionConfig$1.createFromParcel(PictureSelectionConfig.java:513)
        at android.os.Parcel.readParcelable(Parcel.java:2796)
        at android.os.Parcel.readValue(Parcel.java:2690)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3057)
        at android.os.BaseBundle.unparcel(BaseBundle.java:257)
        at android.os.BaseBundle.getInt(BaseBundle.java:961)
        at android.content.Intent.getIntExtra(Intent.java:7013)
        at com.luck.picture.lib.PicturePreviewActivity.initWidgets(PicturePreviewActivity.java:142)`

**Comment by MinhNNDev** [comment]
> Yes I am also facing same issue in Android. below crash log show error in PicturePreviewActivity
> ` java.lang.NoClassDefFoundError: Failed resolution of: Lcom/luck/picture/lib/config/UCropOptions; at com.luck.picture.lib.config.PictureSelectionConfig.<init>(PictureSelectionConfig.java:477) at com.luck.picture.lib.config.PictureSelectionConfig$1.createFromParcel(PictureSelectionConfig.java:516) at com.luck.picture.lib.config.PictureSelectionConfig$1.createFromParcel(PictureSelectionConfig.java:513) at android.os.Parcel.readParcelable(Parcel.java:2796) at android.os.Parcel.readValue(Parcel.java:2690) at android.os.Parcel.readArrayMapInternal(Parcel.java:3057) at android.os.BaseBundle.unparcel(BaseBundle.java:257) at android.os.BaseBundle.getInt(BaseBundle.java:961) at android.content.Intent.getIntExtra(Intent.java:7013) at com.luck.picture.lib.PicturePreviewActivity.initWidgets(PicturePreviewActivity.java:142)`

**Comment by MinhNNDev** [comment]
I solved this problem by turn off PicturePreview.

**Comment by baronha** [comment]
I will review PicturePreviewActivity
